import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans-loaded",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono-loaded",
  display: "swap",
  weight: ["400", "500", "600"],
});

// Display font — Satoshi Variable (Indian Type Foundry / Fontshare FFL).
// Geometric sans in the Aeonik-Pro-adjacent tradition; free for commercial
// use under the Fontshare Free Font License. One variable-font file
// (~43 KB) covers the full 300–900 weight range, so we load a single
// asset instead of per-weight splits.
//
// next/font/local handles the performance hygiene automatically:
// - rel=preload link is injected into <head> when the variable is used
// - font-display: swap is applied
// - Size-adjusted fallback metrics are generated (see `fallback`) so
//   the Inter fallback renders at visually matching x-height and
//   ascent/descent — prevents CLS on the font swap.
const display = localFont({
  src: "../../public/fonts/Satoshi-Variable.woff2",
  variable: "--font-display-loaded",
  display: "swap",
  weight: "300 900",
  style: "normal",
  fallback: ["Inter", "Helvetica Neue", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: {
    default: "NordPush – Deine SEO Agentur für mehr Sichtbarkeit im Web",
    template: "%s",
  },
  description:
    "SEO-Strategien, die messbare Ergebnisse liefern. Keyword-Recherche, Konkurrenzanalyse, technisches SEO und Content-Aufbau – aus einer Hand.",
  metadataBase: new URL("https://nordpush.de"),
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48", type: "image/x-icon" },
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  manifest: "/manifest.webmanifest",
  openGraph: {
    type: "website",
    locale: "de_DE",
    url: "https://nordpush.de",
    siteName: "NordPush",
    title: "NordPush – Deine SEO Agentur für mehr Sichtbarkeit im Web",
    description:
      "Messbare SEO-Ergebnisse aus Neumünster. Strategien, die echte Kunden liefern.",
    // `images` intentionally omitted here: Next.js 15 auto-merges the PNG
    // generated by src/app/opengraph-image.tsx (1200×630, brand-coloured)
    // into the openGraph metadata whenever no explicit images array is
    // provided. The previous explicit "/og-default.svg" reference (a)
    // pointed at an SVG that some social crawlers (LinkedIn, legacy Slack)
    // reject, and (b) overrode the generated PNG. claude-seo L2.
  },
  twitter: {
    card: "summary_large_image",
    title: "NordPush – Deine SEO Agentur",
    description: "Mehr Sichtbarkeit. Mehr Kunden. SEO, das Ergebnisse liefert.",
    // Same rationale as openGraph.images above — Next.js pulls from
    // src/app/twitter-image.tsx automatically when `images` is absent.
  },
};

export const viewport: Viewport = {
  // Explicit viewport scaling to protect against future Next.js default
  // changes. Next.js currently ships "width=device-width, initial-scale=1"
  // by default, but making it explicit is safer and removes the
  // claude-seo L1 finding.
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#191c1f" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de">
      <body className={`${sans.variable} ${mono.variable} ${display.variable}`}>{children}</body>
    </html>
  );
}
